Fixes #2 Creation of Internships.md
ai-cfia/ai-cfia-ia-acia.github.io pull request #18
Opened 2023-09-28 19:30 UTC by melanie-fressard

Creation of the md file internships that highlight the positive experiences of interns

2023-10-03 18:59 UTC, melanie-fressard commented
Est ce que comme ça c'est ok pour vous où est ce que je met sous forme de Q&A ?

2023-10-05 19:55 UTC, JolanThomassin approved these changes

2023-10-05 19:58 UTC, rngadam requested changes

2023-10-05 19:58 UTC, rngadam commented on ai-cfia-ia-acia/docs/about/team/internships.md
> +> L'intégration dans l'entreprise est honnêtement incroyable. On nous demande d'être présent dans la promotion de l'agence, on nous demande d'aller voir des agriculteurs pour leur parler du projet, o
pas agriculteurs, inspecteurs

2023-10-05 20:30 UTC, RussellJimmies requested changes

2023-10-05 20:30 UTC, RussellJimmies commented on ai-cfia-ia-acia/docs/about/team/internships.md
> +> Le processus d'intégration m'a semblé décousu, comme dans une start-up. Je m'attendais à quelque chose de plus structuré, étant un poste au gouvernement fédéral. En fait, ce n'est pas mal structuré
J'enlèverais ce bloc de texte, c'était plutôt destiné à la coordonnatrice de stage.

2023-10-05 20:30 UTC, RussellJimmies commented on ai-cfia-ia-acia/docs/about/team/internships.md
> +> Nos supérieurs nous ont fait comprendre que nous avons une place et qu'ils veulent notre apport, que nous sommes les bienvenus au sein de l'équipe
Ajouter un point à la fin de la phrase

2023-10-05 20:30 UTC, RussellJimmies commented on ai-cfia-ia-acia/docs/about/team/internships.md
> +> Travaillant avec le gouvernement, nous avons été soumis à de nombreuses enquêtes de sécurité et avons dû respecter des restrictions initiales sur nos environnement de travail mais nous sommes relat
Ajouter un "S" à environnement**s** de travail

Enlever le "S" à rend

2023-10-05 20:33 UTC, RussellJimmies commented on ai-cfia-ia-acia/docs/about/team/internships.md
> +> Le processus d'intégration m'a semblé décousu, comme dans une start-up. Je m'attendais à quelque chose de plus structuré, étant un poste au gouvernement fédéral. En fait, ce n'est pas mal structuré
This block of text ↓
"Le processus d'intégration m'a semblé décousu, comme dans une start-up. Je m'attendais à quelque chose de plus structuré, étant un poste au gouvernement fédéral. En fait, ce n'est pas mal structuré, c'est en construction et nous avons tous notre part à jouer pour améliorer le processus."

2023-10-07 12:42 UTC, rngadam approved these changes

2023-10-10 11:55 UTC, redat97 approved these changes

2023-10-10 13:27 UTC, k-allagbe approved these changes

2023-10-10 13:58 UTC, RussellJimmies approved these changes

2023-10-10 15:03 UTC, merged