Issue  #77: Introduction Bryan Ndjeutcha
ai-cfia/ai-cfia-ia-acia.github.io pull request #78
Opened 2024-04-30 18:34 UTC by snakedye

Tasks:

* [x] Update the introduction page in both French and English.

Acceptance Criteria:

* [x] The introduction should be professional, reflecting the employee's role within the team and outlining their professional journey.
* [x] It should contains linkedin link and mail

https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/issues/62

2024-04-30 20:17 UTC, ThomasCardin requested changes

2024-04-30 20:17 UTC, ThomasCardin commented on docs/about/team/internships.md
> +> l'innovation et laprise d'initiative. On a très vite l'impression d'être
la prise (typo)

2024-04-30 20:17 UTC, ThomasCardin commented on docs/about/team/internships.md
> +> J'ai aussi del'expérience dans le développement de logiciel backend,
de l'expérience (typo)

2024-04-30 20:18 UTC, SonOfLope requested changes

2024-04-30 20:18 UTC, SonOfLope commented on docs/about/team/the-software-development-team.md
> +### [Ndjeutcha, Bryan](https://www.linkedin.com/in/lopez-jonathan/) - DevSecOps
Change role to Backend

2024-05-07 19:38 UTC, snakedye commented
Any update on this?

2024-05-07 20:36 UTC, RussellJimmies requested changes

2024-05-07 20:36 UTC, RussellJimmies commented on docs/about/team/internships.md
> +> Lors de la journée d'intégration au CFIA, j'ai été introduit au projet,
```suggestion
> Lors de la journée d'intégration à l'ACIA, j'ai été introduit au projet,
```

2024-05-09 15:26 UTC, SonOfLope approved these changes

2024-05-13 18:33 UTC, snakedye commented
@ibrahim-kabir it's up to you.

2024-05-15 12:56 UTC, SonOfLope commented
@snakedye you can also re-request review from reviewers who asked for changes  : 
![image](https://github.com/ai-cfia/ai-cfia-ia-acia.github.io/assets/73133692/a9d5e830-8971-4402-a4a7-d2295c5c1c35)

2024-05-15 18:11 UTC, RussellJimmies approved these changes

2025-03-27 18:09 UTC, closed without merging